defmodule MyHive.Accounts.Services.CvPdfRenderer do

  alias MyHive.Accounts.Services.CvHtmlRenderer
  import MyHive.Accounts.Services.CvHtmlHeaderRenderer

  def call(fields) do
    CvHtmlRenderer.call(fields)
    |> PdfGenerator.generate(
      page_size: "A4",
      shell_params: shell_params(fields)
    )
  end

  def timestamp() do
    String.replace(current_time(), "/","_")
    |> String.replace(":","_")
    |> String.replace(" ","_")
  end

  defp shell_params(_fields) do
    ["-O", "Portrait",
     "--margin-top", "15",
     "--margin-bottom", "30",
     "--footer-spacing", "6",
     "--margin-left", "20",
     "--margin-right", "20",
     "--footer-font-size", "8",
     "--footer-center", "[page] of [topage]",
     "--footer-right","Generated by my-hive #{current_time()}"]
  end

  defp current_time do
    {_, time} = Timex.now("Europe/London")
      |> Timex.format("%m/%d/%Y %H:%m:%S", :strftime)
    time
  end

  def name_field(fields) do
    Enum.filter(fields, fn ufield ->
      ufield.cv_field.name == "Name"
    end) |> List.first
  end

  def position_field(fields) do
    Enum.filter(fields, fn ufield ->
      ufield.cv_field.name == "Current position"
    end) |> List.first
  end

  def header(fields) do
    name = name_field(fields).field_value
    position = position_field(fields).field_value
    {:ok, hpath} = Briefly.create
    File.write!(hpath, render_header(name, position))    
    hpath
  end


end
